In [6]:
import os
import sys
import pickle
sys.path.append(os.path.abspath('..'))

import numpy as np
from src.qubo import build_qubo
from src.ising import qubo_to_ising

In [7]:
with open('results/raw/instance_data.pkl', 'rb') as f:
    data_n1 = pickle.load(f)

scenarios = data_n1['scenarios']
alpha = data_n1['alpha']
print("Data instance berhasil di-load!")
print(f"alpha: {alpha} | scenarios = {scenarios}" )

Data instance berhasil di-load!
alpha: [[[0.   0.25 0.25 ... 0.1  0.1  0.1 ]
  [0.25 0.   0.25 ... 0.1  0.1  0.1 ]
  [0.25 0.25 0.   ... 0.1  0.1  0.1 ]
  ...
  [0.1  0.1  0.1  ... 0.   0.   0.  ]
  [0.1  0.1  0.1  ... 0.   0.   0.  ]
  [0.1  0.1  0.1  ... 0.   0.   0.  ]]

 [[0.   0.22 0.22 ... 0.1  0.1  0.1 ]
  [0.22 0.   0.22 ... 0.1  0.1  0.1 ]
  [0.22 0.22 0.   ... 0.1  0.1  0.1 ]
  ...
  [0.1  0.1  0.1  ... 0.   0.   0.  ]
  [0.1  0.1  0.1  ... 0.   0.   0.  ]
  [0.1  0.1  0.1  ... 0.   0.   0.  ]]

 [[0.   0.18 0.18 ... 0.08 0.08 0.08]
  [0.18 0.   0.18 ... 0.08 0.08 0.08]
  [0.18 0.18 0.   ... 0.08 0.08 0.08]
  ...
  [0.08 0.08 0.08 ... 0.   0.   0.  ]
  [0.08 0.08 0.08 ... 0.   0.   0.  ]
  [0.08 0.08 0.08 ... 0.   0.   0.  ]]

 ...

 [[0.   0.   0.   ... 0.07 0.07 0.07]
  [0.   0.   0.   ... 0.07 0.07 0.07]
  [0.   0.   0.   ... 0.07 0.07 0.07]
  ...
  [0.07 0.07 0.07 ... 0.   0.16 0.16]
  [0.07 0.07 0.07 ... 0.16 0.   0.16]
  [0.07 0.07 0.07 ... 0.16 0.16 0.  ]]

 [[0.   0. 

In [8]:
m = 30              # Jumlah aksi (qubits)
costs = np.ones(m)  # Asumsi cost seragam untuk eksperimen MVD
budget = 5.0        # Batas anggaran
eta = 10.0          # Multiplier penalti anggaran

In [9]:
q, Q, const = build_qubo(scenarios, alpha, costs, budget, eta)
K, g, c_ising = qubo_to_ising(q, Q, const)

print("QUBO Linear Terms (q):", q.shape)
print("QUBO Quadratic Terms (Q):", Q.shape)
print("Konstanta Ising:", c_ising)

QUBO Linear Terms (q): (30,)
QUBO Quadratic Terms (Q): (30, 30)
Konstanta Ising: 1094.644909190374


In [10]:
with open('results/raw/qubo_ising_data.pkl', 'wb') as f:
    pickle.dump({
        'q': q, 'Q': Q, 'const': const,
        'K': K, 'g': g, 'c_ising': c_ising
    }, f)
print("Data QUBO dan Ising berhasil disimpan ke pickle!")

Data QUBO dan Ising berhasil disimpan ke pickle!
